version: '3.6'  
services:  
  app:
    build:
      context: ./reto
    command: bash -c "sleep 5 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db
    ports:
      - "8000:8000"
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Poll_DB
