version: '3.6'  
services:  
  app:
    build:
      context: ./reto
    depends_on:
      - postgres_db
    environment:
      - POSTGRES_HOST=postgres_db
    ports:
      - "8000:8000"
  postgres_db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgress
      - POSTGRES_DB=Poll_DB
    ports:
      - "5532:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes: 
  pgdata:

