version: '3.6'  
services:  
  app_poll:
    build:
      context: ./reto_poll
    command: bash -c "sleep 30 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      - POSTGRES_HOST=db_poll
      - POSTGRES_USER=postgres
      - POSTGRES_PWD=postgres
      - RABBITMQ_HOST=broker
    depends_on:
      - db_poll
      - broker
  db_poll:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Poll_Vote_DB
  app_stats:
    build:
      context: ./reto_stat
    command: bash -c "./start_process.sh"
    environment:
      - POSTGRES_HOST=db_stats 
      - POSTGRES_USER=postgres
      - POSTGRES_PWD=postgres
      - RABBITMQ_HOST=broker
    depends_on:
      - db_stats
      - broker
  db_stats:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Poll_Stats_DB
  broker:
    image: rabbitmq:3
  web:
    image: nginx
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf.template
    ports:
      - "80:80"
    depends_on:
      - app_stats
      - app_poll
    environment:
      - GET_HOST=app_stats
      - PUT_HOST=app_poll
      - THIS_HOST=web
    command: /bin/bash -c "envsubst '$${GET_HOST},$${PUT_HOST},$${THIS_HOST}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"

