# Generated by Django 2.1.3 on 2018-12-01 22:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_pollvote_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollHourStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('votes', models.IntegerField(default=0)),
                ('vote_hour', models.DateTimeField()),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hourstat', to='poll.PollOption')),
            ],
            options={
                'verbose_name': 'Hour Stat',
                'verbose_name_plural': 'Hour Stats',
                'db_table': 'poll_hour_stat',
            },
        ),
        migrations.CreateModel(
            name='PollStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('votes', models.IntegerField(default=0)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stat', to='poll.PollOption')),
            ],
            options={
                'verbose_name': 'Stat',
                'verbose_name_plural': 'Stats',
                'db_table': 'poll_stat',
            },
        ),
    ]
