# Generated by Django 2.1.3 on 2018-12-02 13:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Poll',
                'verbose_name_plural': 'Polls',
                'db_table': 'poll',
            },
        ),
        migrations.CreateModel(
            name='PollHourStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('votes', models.IntegerField(default=0)),
                ('vote_hour', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Hour Stat',
                'verbose_name_plural': 'Hour Stats',
                'db_table': 'poll_hour_stat',
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('option_name', models.CharField(blank=True, default='', max_length=100)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='poll', to='poll.Poll')),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
                'db_table': 'poll_option',
            },
        ),
        migrations.CreateModel(
            name='PollStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('votes', models.IntegerField(default=0)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stat', to='poll.PollOption')),
            ],
            options={
                'verbose_name': 'Stat',
                'verbose_name_plural': 'Stats',
                'db_table': 'poll_stat',
            },
        ),
        migrations.AddField(
            model_name='pollhourstat',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hourstat', to='poll.PollOption'),
        ),
    ]
